version: '3'
services:
  routescoop-web:
    build: ./routescoop-web
    restart: always
    depends_on:
      - routescoop-api
    ports:
      - 9000:9000
    env_file:
      - routescoop.env
    environment:
      - JAVA_OPTS=-Xms256m -Xmx256m
  routescoop-api:
    build: ./routescoop-api
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 9001:9000
    env_file:
      - routescoop.env
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1g
      - STRAVA_ACTIVITY_PAGE_SIZE=200
    links:
      - mysqldb:mysqldb.local
  mysqldb:
    image: mysql:5.7.16
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=routescoop
