FROM        pelawler/activator

COPY        ["build.sbt", "/tmp/build/"]
COPY        ["project/plugins.sbt", "project/build.properties", "/tmp/build/project/"]
RUN         cd /tmp/build && \
            activator compile && \
            rm -rf /tmp/build

# copy code
COPY        . /routescoop-web
WORKDIR     /routescoop-web
RUN         activator compile && activator test:compile
CMD         ["activator"]
